### ISSUE TITLE
SetPolarity function in cpp file

### ISSUE THREAD

**Issue by RadioMCMLVI** [SV-Zanshin/DS1631#13]
Function doesn't work as expected.

## Actual Behavior
Whatever the value received in the _polarity_ variable, the operation of Tout output is not modified.

The problem is identified in lines 195-196:
  _writeByte(_Devices[device], DS1631_ACCESS_CONFIG,
            (readByte(_Devices[device], DS1631_ACCESS_CONFIG) & 0xFD) & (polarity << 1));_

## Steps to Reproduce the Problem
Modify the logical operator for injecting the _polarity_ variable (AND -> OR).
  _writeByte(_Devices[device], DS1631_ACCESS_CONFIG,
            (readByte(_Devices[device], DS1631_ACCESS_CONFIG) & 0xFD) | (polarity << 1));_

After doing this, Tout pin works as expected.

## Specifications
  - Library Version: 1.0.4
  - IDE Version: Arduino 1.8.19
  - Platform: Linux Mint Linux Mint 20.3 Una, but the problem is platform independent.

**Comment by SV-Zanshin** [comment]
I've made the corrections in your name - Thanks for catching that!
